#!/bin/bash
cd /etc/hostsVN
echo "Đang tải hostsVN từ Github"
wget --no-check-certificate https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hosts-iOS
cp -a hosts-iOS /etc/hosts
rm -rf hosts-iOS
echo "Respring thiết bị để hoàn tất!"
exit 0
