#!/bin/bash

if [[ $1 == remove || $1 == abort-install ]]; then

echo "Đang khôi phục tập tin hosts..."
cp -a /etc/hostsVN/originalhosts /etc/hosts
echo "Đã khôi phục xong!"
chown root:wheel /etc/hosts
chmod 644 /etc/hosts
echo "Khởi động lại mDNSResponder..."
killall -9 mDNSResponder
killall -9 mDNSResponderHelper
echo "Dọn dẹp cho sạch..."
rm -rf /etc/hostsVN
echo "Respring thiết bị để hoàn tất!"
exit 0

else

exit 0

fi
